define({
  root: ({
    zoom2message: "Clic para hacer Zoom al Resultado",
    addresslabel: "Dirección",
    coordslabel: "Coordenadas",
    addressinsplabel: "Inspector",
    resultslabel: "Resultados",
    locateDescLabel: "Ingrese una dirección:",
    coordDescLabel: "Ingrese las coordenadas:",
    reverseDescLabel: "Use la herramienta de inspección de direcciones para hacer clic en el mapa y ubicar la dirección",
    removeresultmessage: "Remover Resultados",
    noresultsfoundlabel: "No se han encontrado Resultados",
    resultsfoundlabel: "Resultados encontrados:",
    clear: "Limpiar",
    widgetversion: "Información mejorada de la versión del widget de localización",
    widgetverstr: "Widget Version",
    wabversionmsg: "Widget is designed to run in Web AppBuilder version",
    revgeocodetip: "Inspeccionar dirección por punto",
    coordUnitLbl: "Unidades:",
    example: "Ejemplo:",
    locate: "Ubicar",
    drawpointtooltip: "Inspeccionar Dirección de Ubicaciones",
    longitude: "Longitud (X)",
    latitude: "Latitud (Y)",
    coordinates: "Coordenadas",
    location: "Ubicación",
    address: "Dirección",
    exampleClickTooltip: "Haga clic para agregar las coordenadas de ejemplo anteriores",
    score: "Score",
    locatorissue: "GeocodeServer Issue",
    locatorissuemessage: "GeocodeServer needs to have a singleLineFieldName.",
    limittomapextent: "Limitar la búsqueda de direcciones a la extensión de mapas.",
    reversegeocodefailtitle: "Inspección de direcciones fallida",
    reversegeocodefailmsg: "Error al buscar una dirección en la ubicación en la que se hizo clic. Inténtalo de nuevo."
  })
});
